### PR TITLE
Migrate to Vite from Create React App #81

### PR DESCRIPTION
**Pull request by Palakkgoyal**
## Related Issue(s)

This is related to issue #81

## Proposed Changes

All the dependencies work fine and the server start by running `npm start`

###For setting up using vite you have to:
- fork the repo and clone it in your system.
- run `npm install`
- run `npm add -D sass`

You are ready to give it a go run `npm start` and the server will run on "localhost:5173"

## Type of Change

- [ ] New Feature (App)

## Your Idea for Level (GSSoC)

- [ ] Level 1
- [x] Level 2
- [ ] Level 3

## Additional Notes

-It is necessary in vite to use .jsx extension if the file uses jsx

### CODE REVIEW

**Comment by praveenscience** [comment]
I am actually planning to test this so let's have this in separate branch... 😊

**Comment by Palakkgoyal** [comment]
Yes, sure

**Comment by Palakkgoyal** [comment]
So, according to me you have to create  a new branch in this repo and I will send a PR to that. Have you created a new branch?

**Comment by praveenscience** [comment]
I need to do it. Will do it soon! 😊

**Comment by praveenscience** [comment]
And don't worry @Palakkgoyal, you're getting a Level 3 for this! ❤️

**Comment by Palakkgoyal** [comment]
Thanks a lot Praveen😄

**Pull request closed without merging**
