### PR TITLE
Added linting to the project

### LINKED ISSUE #63: 🚀 [New Feature_WebApp] - Setup Linting
### Description of the enhancement. ✍🏻

We can setup linting so that the code is well-organized and readable. Also, this will help us to maintain the code style throughout the codebase.

### Describe briefly how you would implement this enhancement.

```bash
This can be achieved using prettier, husky and eslint.
```

### Screenshots Example (if applicable)

_No response_

### Additional information

_No response_

### Contributor terms

- [X] I agree to follow the Contributing Instructions

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
* Used prettier to format code on save
* Used eslint to check for linting issues
* Used husky to configure pre-commit hook

Fixes #63

### CODE REVIEW

**Comment by AmanJain18** [comment]
@praveenscience Check this one, he added the lint work, to make code prettier.
LGTM, Just check if u have any more suggestions into it.

**Comment by praveenscience** [comment]
Ah, amazing, it's husky... But the problem is, can we have `"` instead of `'` please. And can we have the same rules as what we're having now?

**Review by praveenscience — CHANGES_REQUESTED** [review]
Ah, amazing, it's husky... But the problem is, can we have `"` instead of `'` please. And can we have the same rules as what we're having now?

**Review by praveenscience — COMMENTED** [review]
I need more time reviewing this... Give me time to test this thing locally! 😊

**Comment by praveenscience** [comment]
Hey @kailashchoudhary11, the `.prettierrc.json` file has some encoding issues, kindly check:
image

**Comment by kailashchoudhary11** [comment]
> Hey @kailashchoudhary11, the `.prettierrc.json` file has some encoding issues, kindly check: image

What are encoding issues?

**Comment by praveenscience** [comment]
Can you re create the `.prettierrc.json` file again? Open it with a hex viewer to see the problem.

**Comment by kailashchoudhary11** [comment]
> Can you re create the `.prettierrc.json` file again? Open it with a hex viewer to see the problem.

Done!

**Comment by kailashchoudhary11** [comment]
> > Can you re create the `.prettierrc.json` file again? Open it with a hex viewer to see the problem.
> 
> Done! @praveenscience

**Pull request closed without merging**
