### PR TITLE
Added "Back to Top " button & Table of Contents (#32)

### LINKED ISSUE #32: Add "Back to top" button in ReadMe.md
Could we add a 'Back to Top' button for contributors' convenience? It would allow users to easily navigate back to the top with a single click. Also, I'd be happy to take on this issue if assigned. Thank you!

### PR DESCRIPTION
**Pull request by Swastik007sharma**
## Related Issue(s)

Closes #32 

## Proposed Changes

Added "Back to Top" button & Table of Content in the `ReadMe.md` file

## Type of Change

- [ ] New Feature (Landing Page)
- [ ] New Feature (App)
- [ ] Bug (Landing Page)
- [ ] Bug (App)
- [ ] New Component (App)
- [ ] Enhancement
- [x] Documentation / ReadMe / Workflows
- Other (If not in above options):  

## Your Idea for Level (GSSoC)

- [ ] Level 1
- [ ] Level 2
- [ ] Level 3

### CODE REVIEW

**Review by praveenscience — CHANGES_REQUESTED** [review]
Amazing, looks good, but hey, let's have text with emoji please? 😊

**Comment by Swastik007sharma** [comment]
> Amazing, looks good, but hey, let's have text with emoji please? 😊

Sure, no problem.

**Review by praveenscience — CHANGES_REQUESTED** [review]
One very small and last thing, remove the brackets, they don't go well with the design. Thanks. 😊 I'll merge this once you do this.

**Review by praveenscience — APPROVED** [review]
👍

**Pull request merged**
