### PR TITLE
PR template with default gssoc23 label

### LINKED ISSUE #2: Create PR Templates
As a part of GSSoC 23, I would like someone to create a PR Template that takes up following options.

1. New Feature (Landing Page)
2. New Feature (App)
3. Bug (Landing Page)
4. Bug (App)
5. New Component (App)
6. Your Idea for Level (GSSoC)
7. Which Issue it Solves?

And it should automatically give the default GSSoC Label. Please explain how you're planning to do it while you wanna grab this issue.

### PR DESCRIPTION
**Pull request by Isha988**
## Related Issue(s)
Closes #2 

## Proposed Changes
PR template file is created and labeler workflow is added.

## Type of Change

- [ ] New Feature (Landing Page)
- [ ] New Feature (App)
- [ ] Bug (Landing Page)
- [ ] Bug (App)
- [ ] New Component (App)
- [ ] Enhancement
- [x] Documentation / ReadMe / Workflows
- [ ] Other (If not in above options):  

## Your Idea for Level (GSSoC)
- [ ] Level 1
- [x] Level 2
- [ ] Level 3

## Additional Notes
Please add gssoc23 label to this so that it can be counted as gssoc contribution

### CODE REVIEW

**Review by praveenscience — APPROVED** [review]
I am not sure if this really works, but let's try it out! 💪🏻

**Comment by praveenscience** [comment]
@Isha988 Seems like it worked! ❤️

**Comment by Isha988** [comment]
> @Isha988 Seems like it worked! ❤️

That's great 👍

**Comment by Isha988** [comment]
@praveenscience Please add the label of level so that the score can be counted correctly.

**Pull request merged**
