### PR TITLE
Added 5 Types of Issue templates and optimize labeler.yml for Issues and PRs

### PR DESCRIPTION
**Pull request by AmanJain18**
## Related Issue(s)

Closes  Issue #1

## Proposed Changes

Added 5 issue templates and optimize labeler.yml for tagging GSSoC2023 Label for pr and Issue simultaneously

## Type of Change

- [ ] New Feature (Landing Page)
- [ ] New Feature (App)
- [ ] Bug (Landing Page)
- [ ] Bug (App)
- [ ] New Component (App)
- [x] Enhancement
- [x] Documentation / ReadMe / Workflows
- Other (If not in above options):  

## Your Idea for Level (GSSoC)

- [ ] Level 1
- [ ] Level 2
- [x] Level 3

### CODE REVIEW

**Comment by AmanJain18** [comment]
Once you merge all the issue will be fixed, tested locally and on different repo... It's occurs due to removal of current labeler file

**Review by praveenscience — CHANGES_REQUESTED** [review]
Why was `package-lock.json` deleted?

**Comment by AmanJain18** [comment]
> Why was `package-lock.json` deleted?

No, it's got updated to sass 9.0.0 due to previous merge requet... it is present

**Comment by AmanJain18** [comment]
image

**Comment by praveenscience** [comment]
I understand, but this PR doesn't have anything to do with node modules right? So `package-lock.json` should not be changed, kindly revert that file alone, or just don't include this file in this PR. 😊

**Comment by arunavabasu-03** [comment]
I would like to work on this!

**Comment by AmanJain18** [comment]
I got ur point but after merger of PR #25, he only changed the package.json due to this whenever we perform git pull, it will be changed to 9.0.0 as package.json has mentioned sass -v 9.0.0 and currently package-lock.json hav sass -v 7.0.3 to avoid package conflict...

**Comment by AmanJain18** [comment]
> 

Kindly ask for issue assign in the "Issues" section rather than in a pull request. Please note that the mentioned issue has already been resolved.

**Comment by AmanJain18** [comment]
> I would like to work on this!

Kindly ask for issue assign in the "Issues" section rather than in a pull request. Please note that the mentioned issue has already been resolved.

**Comment by AmanJain18** [comment]
> I understand, but this PR doesn't have anything to do with node modules right? So `package-lock.json` should not be changed, kindly revert that file alone, or just don't include this file in this PR. 😊

Reverted back to previous version

**Review by praveenscience — CHANGES_REQUESTED** [review]
The `package-lock.json` keeps coming in again and again. Do one thing, get the `package-lock.json` from the latest `main` branch and add to this... Let's get this merged soon! 💪

**Comment by AmanJain18** [comment]
Fixed the `package-lock.json` file by getting it from the latest `main` branch

**Comment by praveenscience** [comment]
Not sure if it's just me. I still see this! 😞 
image

**Comment by praveenscience** [comment]
Na, I tried in local, errors due to `package-lock.json` came up, plus, this commit is not clean, as what it says! 😊 Don't worry, I'll fix it for you! 😊

**Review by praveenscience — APPROVED** [review]
👍

**Comment by praveenscience** [comment]
Not your fault, really! GitHub's it is...

**Comment by AmanJain18** [comment]
image
Getting this  6 commit ahead after the merger of this PR in my fork repo after syncing the repo.
should i create another PR resolve this ?
cc @praveenscience

**Pull request merged**
