### PR TITLE
Updated Contributing.md

### LINKED ISSUE #1: Create an Issue Template
As a part of GSSoC 23, I would like someone to create an Issue Template that gives the following choices.

1. New Feature (Landing Page)
2. New Feature (App)
3. Bug (Landing Page)
4. Bug (App)
5. New Component (App)

And it should automatically give the default GSSoC Label. Please explain how you're planning to do it while you wanna grab this issue.

### PR DESCRIPTION
**Pull request by DSR1729**
* Added Raising Issue template

Fixes #1

### CODE REVIEW

**Review by praveenscience — CHANGES_REQUESTED** [review]
No, I asked you to create an Issue Template, not edit `Contributing.md`. Can you please fix it? Kindly check out: [Configuring issue templates for your repository - GitHub Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

**Comment by DSR1729** [comment]
Yeah sure, I can do it👍

**Comment by DSR1729** [comment]
hey @praveenscience while creating an issue template, this is 👇 showing up , what should I do ??
Screenshot 2023-05-28 at 02-27-23 New File at _ · DSR1729_GitHub-ReadMe

**Comment by AmanJain18** [comment]
> No, I asked you to create an Issue Template, not edit `Contributing.md`. Can you please fix it? Kindly check out: [Configuring issue templates for your repository - GitHub Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

I know how to make such a type of templates, assign it to me if possible @praveenscience

**Comment by praveenscience** [comment]
@DSR1729 Shall we ask @AmanJain18 to do this as you may not have the idea? You can learn from him. 😁

**Pull request closed without merging**
