### PR TITLE
node-sass upgraded

### LINKED ISSUE #22: Upgrade node-sass version
Hi @praveenscience, node-sass version is deprecated. This needs to be upgraded so that the application can be run in local.

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
### Description: 

- node-sass updated to `9.0.0` version

### CODE REVIEW

**Review by praveenscience — CHANGES_REQUESTED** [review]
Sorry, what I meant is, have only the `package.json` as change. 😊

**Comment by gurjeetsinghvirdee** [comment]
Check now

**Review by praveenscience — APPROVED** [review]
Wow, did I mess up this level? And is this really working now? 🤔

**Comment by gurjeetsinghvirdee** [comment]
> Wow, did I mess up this level? And is this really working now? 🤔

Humans do mistake some times ❤️, now it's working

**Pull request merged**
